name: CI Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]
    
    name: Build with Java ${{ matrix.java }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean install -B -Dgpg.skip=true -Dmaven.javadoc.skip=true
    
    - name: Run tests
      run: mvn test -B
    
    - name: Verify distribution
      run: mvn distribution-verifier:verify -B -DdistributionFile=target/test-classes/valid-fullmatch/valid_fullmatch.zip -DwhitelistFile=target/test-classes/valid-fullmatch/whitelist.xml